<a href="https://colab.research.google.com/github/mk7890/Python_Data_Analysis/blob/main/NumPy_day3_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

31. How to ignore all numpy warnings (not recommended)?

In [ ]:
# 31. How to ignore all numpy warnings (not recommended)?
import numpy as np


32. Is the following expressions true?

In [ ]:
# 32. Is the following expressions true?
import numpy as np
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-2-b71759f88047>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

33. How to get the dates of yesterday, today and tomorrow?

In [ ]:
# 33. How to get the dates of yesterday, today and tomorrow?
import numpy as np
print(np.datetime64('today'))
print(np.datetime64('today') - np.timedelta64(1))
print(np.datetime64('today') + np.timedelta64(1))

2024-10-31
2024-10-30
2024-11-01


34. How to get all the dates corresponding to the month of July 2016?

In [ ]:
# 34. How to get all the dates corresponding to the month of July 2016?
import numpy as np
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [ ]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?
import numpy as np
A = -10
B = 20
answer = ((A+B)*(-A/2))
print(answer)

B = np.add(A,B)
A = np.divide(A,2)
A = np.negative(A)
A = np.multiply(A,B)
print(A)

50.0
50.0


36. Extract the integer part of a random array of positive numbers using 4 different methods

In [ ]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods
import numpy as np
z = np.random.randint(0,10,20)
print(z)


[4 0 8 2 5 0 3 1 8 1 6 7 0 8 2 3 3 3 9 3]
[4 0 8 2 5 0 3 1 8 1 6 7 0 8 2 3 3 3 9 3]
[4 0 8 2 5 0 3 1 8 1 6 7 0 8 2 3 3 3 9 3]
[4 0 8 2 5 0 3 1 8 1 6 7 0 8 2 3 3 3 9 3]
[4. 0. 8. 2. 5. 0. 3. 1. 8. 1. 6. 7. 0. 8. 2. 3. 3. 3. 9. 3.]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [ ]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4
import numpy as np
matrix = np.random.randint(0,4,25).reshape(5,5)
print(matrix)


[[2 0 3 1 1]
 [2 2 0 3 1]
 [0 0 0 1 0]
 [0 2 2 3 2]
 [1 1 1 1 3]]


38. Consider a generator function that generates 10 integers and use it to build an array

In [ ]:
# 38. Consider a generator function that generates 10 integers and use it to build an array
import numpy as np
def generate1():
    return np.random.randint(0,10,10)
arr = np.array(generate1())

print(arr)

[6 9 7 3 0 4 2 1 8 4]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [ ]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
import numpy as np
Z = np.linspace(0,1,11,endpoint=False)
print(Z)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it

In [ ]:
# 40. Create a random vector of size 10 and sort it
import numpy as np
z = np.random.uniform(10,50,10)
print(z.astype(int))
z.sort()
print(z.astype(int))

[28 25 15 20 26 40 26 15 22 15]
[15 15 15 20 22 25 26 26 28 40]


41. How to sum a small array faster than np.sum?

In [ ]:
# 41. How to sum a small array faster than np.sum?
import numpy as np
z = np.arange(10)
np.add.reduce(z)

45

42. Consider two random array A and B, check if they are equal

In [ ]:
# 42. Consider two random array A and B, check if they are equal
import numpy as np
A = np.array([5,2,4,6,4,5,5])
B = np.array([5,2,9,7,6,4,6])

equal = np.array_equal(A,B)
print(equal)

False


43. Make an array immutable (read-only)

In [ ]:
# 43. Make an array immutable (read-only)
import numpy as np
Z = np.arange(10)
Z.flags.writeable = False
Z[2]=9
z

ValueError: assignment destination is read-only

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [ ]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
import numpy as np
matrix = np.random.randint((1,20,20))
matrix

array([ 0, 18, 15])

45. Create random vector of size 10 and replace the maximum value by 0

In [ ]:
# 45. Create random vector of size 10 and replace the maximum value by 0
import numpy as np
vector = np.arange(1,11,1)
vector
vector[10] = 0
vector

IndexError: index 10 is out of bounds for axis 0 with size 10