<a href="https://colab.research.google.com/github/mk7890/Python_Data_Analysis/blob/main/NumPy_day1_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import the numpy package under the name np

import numpy as np

In [ ]:
# Print the numpy version and the configuration

import numpy as np
np.__version__

'1.26.4'

In [ ]:
# Create a null vector of size 10
import numpy as np
myVector = np.zeros(10)
print(myVector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#How to find the memory size of any array
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90])
print(f"Array size : {arr.size}") #prints the size of the array
print(f"Array Memory Size : {arr.itemsize}") #prints the memory size of the array



Array size : 9
Array Memory Size : 8


In [ ]:
# How to get the documentation of the numpy add function from the command line
import numpy as np
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [ ]:
from re import X
# Create a null vector of size 10 but the fifth value which is 1
import numpy as np
X = np.zeros(10)
x[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# Create a vector with values ranging from 10 to 49
import numpy as np
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Reverse a vector (first element becomes last)

import numpy as np
import array
x=[10,20,30,40,50]
x.reverse()
print(x)

[50, 40, 30, 20, 10]


In [ ]:
# Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
myMatrix = np.arange(0,9).reshape(3,3)

print(myMatrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
arr = np.array([1,2,0,0,4,0])

print(np.nonzero(arr))


(array([0, 1, 4]),)


In [ ]:
# Create a 3x3 identity matrix
import numpy as np
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Create a 3x3x3 array with random values
import numpy as np
import random
arr = np.random.randint(0, 10, (3,3,3))
print(arr)

[[[8 3 2]
  [5 8 2]
  [7 8 8]]

 [[5 0 9]
  [0 3 9]
  [3 6 9]]

 [[4 7 8]
  [7 4 5]
  [1 7 6]]]


In [ ]:
#Create a 10x10 array with random values and find the minimum and maximum values
import numpy as np
import random

arr = np.random.randint(0,100,(10,10))
print(f"array: {arr}")
print(f"minimum value in array: {arr.min()}")
print(f"maximum value in array: {arr.max()}")

array: [[81 78 75 59 98 55 91 21  7 27]
 [39 66  4 44 88 17 36 57 84 66]
 [25  7 29 51 43 94 66 21 34 66]
 [66 68 51 46 40 44 67 51 44 18]
 [68 70 67 93 10  3 74  7 20 94]
 [75 45 13 33 37 70 98 97 46 13]
 [76 14 31 74 24 24 28 30 43 82]
 [65 92 96 10 20 32 81 64 45 89]
 [73 56 88  3 88 26 38 59 15 24]
 [24 22 86 60 50 59 95 19  4 72]]
minimum value in array: 3
maximum value in array: 98


In [ ]:
# Create a random vector of size 30 and find the mean value
import numpy as np
import random
vector = np.random.random(30)
print(f"vector : {vector}")
print(f"mean : {vector.mean()}")


vector : [0.06999332 0.1870551  0.69602836 0.57551593 0.64317107 0.18088335
 0.55250582 0.41907729 0.4341001  0.95296547 0.01675588 0.90537974
 0.0864906  0.99367229 0.3213428  0.54335284 0.60354677 0.31754905
 0.86671381 0.95616791 0.37177487 0.79930308 0.48269934 0.15555716
 0.80758719 0.85315584 0.61000677 0.15967162 0.13075172 0.42818492]
mean : 0.5040320007201139


In [ ]:
# Create a 2d array with 1 on the border and 0 inside
import numpy as np
arr = np.ones((5,5))
print(arr)
arr[1:-1,1:-1]=0
print()
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
