<a href="https://colab.research.google.com/github/mk7890/Python_Data_Analysis/blob/main/Numpy_Weekly_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

61. Find the nearest value from a given value in an array

In [ ]:
# 61. Find the nearest value from a given value in an array
import numpy as np

# Sample array
arr = np.array([10, 20, 30, 40, 50])

# Given value
value = 33

# Find the nearest value
nearest_value = arr[np.abs(arr - value).argmin()]

print(f"The nearest value to {value} is {nearest_value}")


The nearest value to 33 is 30


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [ ]:
# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
import numpy as np

# Define two arrays
a = np.array([[1, 2, 3]])   # Shape (1, 3)
b = np.array([[4], [5], [6]])  # Shape (3, 1)

# Create an iterator with broadcasting
it = np.nditer([a, b, None])

# Sum the arrays element-wise using the iterator
for x, y, z in it:
    z[...] = x + y

# Get the result from the iterator
result = it.operands[2]

print("Array a:\n", a)
print("Array b:\n", b)
print("Result of a + b:\n", result)


Array a:
 [[1 2 3]]
Array b:
 [[4]
 [5]
 [6]]
Result of a + b:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


63. Create an array class that has a name attribute

In [ ]:
# 63. Create an array class that has a name attribute
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="Unnamed"):
        # Create a new instance of the class, which is essentially an ndarray
        obj = np.asarray(input_array).view(cls)
        # Add the 'name' attribute to the array object
        obj.name = name
        return obj

    def __str__(self):
        # Custom string representation to include the name of the array
        return f"NamedArray(name={self.name}, data={super().__str__()})"

# Create a NamedArray instance
arr = NamedArray([1, 2, 3, 4], name="MyArray")

# Access the name attribute
print(f"Array name: {arr.name}")
# Print the array using the custom string method
print(arr)


Array name: MyArray
NamedArray(name=MyArray, data=[1 2 3 4])


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)

In [ ]:
# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)
import numpy as np

# Given vectors
vector = np.array([10, 20, 30, 40, 50])  # original vector
indices = np.array([1, 3, 1, 2])         # indices where we want to add 1 (with repetition)

# Add 1 to each element in 'vector' indexed by 'indices'
np.add.at(vector, indices, 1)

# Print the modified vector
print("Modified vector:", vector)


Modified vector: [10 22 31 41 50]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [ ]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
import numpy as np

# Given vector X and index list I
X = np.array([10, 20, 30, 40])  # Values to accumulate
I = np.array([0, 2, 2, 1])      # Indices in F where X elements should be added

# Initialize the target array F with zeros (or any other initial value)
F = np.zeros(3)  # F will have 3 elements based on the indices in I

# Accumulate elements of X to F based on indices in I
np.add.at(F, I, X)

# Print the accumulated array F
print("Accumulated array F:", F)


Accumulated array F: [10. 40. 50.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [ ]:
# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
import numpy as np

# Example image (w, h, 3) with dtype=ubyte
image = np.random.randint(0, 256, size=(4, 4, 3), dtype=np.uint8)  # Example image

# Reshape the image to (w*h, 3) to consider each pixel as a row of RGB values
pixels = image.reshape(-1, 3)

# Find unique rows (RGB combinations)
unique_colors = np.unique(pixels, axis=0)

# Print the number of unique colors
print("Number of unique colors:", unique_colors.shape[0])


Number of unique colors: 16


67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [ ]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once?
import numpy as np

# Example 4D array (shape: (w, h, d, e))
arr = np.random.randint(0, 10, size=(2, 3, 4, 5))

# Sum over the last two axes (axis -2 and -1)
result = np.sum(arr, axis=(-2, -1))

# Print the result
print("Shape of the original array:", arr.shape)
print("Shape of the result:", result.shape)
print("Result:\n", result)


Shape of the original array: (2, 3, 4, 5)
Shape of the result: (2, 3)
Result:
 [[ 75 112  94]
 [ 76  91  86]]


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [ ]:
# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?
import numpy as np

# Example vector D (data) and S (subset indices)
D = np.array([10, 20, 30, 40, 50])  # Data vector
S = np.array([0, 1, 0, 1, 0])       # Subset indices

# Compute the sum of elements in each subset (grouped by S)
subset_sums = np.bincount(S, weights=D)

# Compute the count of elements in each subset (grouped by S)
subset_counts = np.bincount(S)

# Compute the mean for each subset (avoid division by zero by ensuring subset_counts > 0)
subset_means = subset_sums / subset_counts

# Print the results
print("Subset means:", subset_means)


Subset means: [30. 30.]


69. How to get the diagonal of a dot product?

In [ ]:
# 69. How to get the diagonal of a dot product?
import numpy as np

# Example arrays A and B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Compute the dot product of A and B
dot_product = np.dot(A, B)

# Extract the diagonal of the dot product
diagonal = np.diagonal(dot_product)

# Print the results
print("Dot product:\n", dot_product)
print("Diagonal of the dot product:", diagonal)


Dot product:
 [[19 22]
 [43 50]]
Diagonal of the dot product: [19 50]


70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [ ]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
import numpy as np

# Original vector
original_vector = np.array([1, 2, 3, 4, 5])

# Calculate the size of the new array
new_size = len(original_vector) + (len(original_vector) - 1) * 3

# Create a new array with zeros
new_vector = np.zeros(new_size, dtype=int)

# Fill the new array with values from the original vector
new_vector[::4] = original_vector

# Print the result
print("New vector:", new_vector)


New vector: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [ ]:
# 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
