<a href="https://colab.research.google.com/github/mk7890/Python_Data_Analysis/blob/main/Numpy_day2_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

16. How to add a border (filled with 0's) around an existing array?

In [ ]:
# 16. How to add a border (filled with 0's) around an existing array?
import numpy as np

arr = np.ones((5,5))
print(f"Original Array :\n\n {arr}")
padded_array = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(f"Padded Array :\n {padded_array}")

Original Array :

 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Padded Array :
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression?

In [ ]:
# 17. What is the result of the following expression?
import numpy as np
'''
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
'''
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.10)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
import numpy as np

arr = np.diag(1+np.arange(4),k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern
import numpy as np

matrix = np.ones((8,8), dtype=int)
matrix[0::2, 0::2]=0
matrix


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element

In [ ]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
import numpy as np

arr=np.random.rand(6,7,8)
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


21. Create a checkerboard 8x8 matrix using the tile function

In [ ]:
# 21. Create a checkerboard 8x8 matrix using the tile function
import numpy as np

pattern=np.array([0,1])
print(f"pattern:\n {pattern}\n")
print(np.tile(pattern, (5,5)))


pattern:
 [0 1]

[[0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]]


22. Normalize a 5x5 random matrix

In [ ]:
# 22. Normalize a 5x5 random matrix
import numpy as np

matrix=np.array([[1,2,3,4,5],
            [1,2,3,4,5],
            [1,2,3,4,5],
            [1,2,3,4,5],
            [1,2,3,4,5]])
print(f"{matrix}\n")
matrix_normalized=(matrix-np.mean(matrix)/(np.std(matrix)))
print(matrix_normalized)


[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]

[[-1.12132034 -0.12132034  0.87867966  1.87867966  2.87867966]
 [-1.12132034 -0.12132034  0.87867966  1.87867966  2.87867966]
 [-1.12132034 -0.12132034  0.87867966  1.87867966  2.87867966]
 [-1.12132034 -0.12132034  0.87867966  1.87867966  2.87867966]
 [-1.12132034 -0.12132034  0.87867966  1.87867966  2.87867966]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [ ]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

import numpy as np
# Define the custom dtype for RGBA colors
dtype_rgba = np.dtype([
                        ('R', np.uint8),
                        ('G', np.uint8),
                        ('B', np.uint8),
                        ('A', np.uint8)])
# Create a Numpy array of RGBA colors using the custom dtype
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=dtype_rgba)
print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [ ]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

import numpy as np

Matrix1=np.arange(15).reshape(5,3)
print(Matrix1)
print()
Matrix2=np.arange(6).reshape(3,2)
print(Matrix2)
print("\ndot product matrix")
print(np.dot(Matrix1,Matrix2))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

[[0 1]
 [2 3]
 [4 5]]

dot product matrix
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [ ]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

import numpy as np

arr = np.arange(11)
print(arr)
print("\n\nNegated array")
arr[(3 < arr) & (arr < 8)] *= -1
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


Negated array
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


26. What is the output of the following script?

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [ ]:
# 26. What is the output of the following script?
import numpy as np

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal?

In [ ]:
# 27. Consider an integer vector Z, which of these expressions are legal?
import numpy as np
'''
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
'''
z=np.arange(10)
print(z**z)
print(2 << z >> 2)
print(z <- z)
print(1j*z)
print(z/1/1)
print(z<z>z)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [ ]:
#28. What are the result of the following expressions?
import numpy as np

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-28-a5b53f05c5fd>:4: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-28-a5b53f05c5fd>:5: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-28-a5b53f05c5fd>:6: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


29. How to round away from zero a float array ?

In [ ]:
# 29. How to round away from zero a float array ?

import numpy as np

z = np.array([-5.5,2.3,1.4,-3.2,-5.3])
print(z)
#zz=np.copysign(np.ceil(np.abs(z)),z)
#print(zz)
z1=np.abs(z)
print(z1)
z2=np.floor(z1)
print(z2)
z3=np.copysign(z2,z)
print(z3)

[-5.5  2.3  1.4 -3.2 -5.3]
[5.5 2.3 1.4 3.2 5.3]
[5. 2. 1. 3. 5.]
[-5.  2.  1. -3. -5.]


30. How to find common values between two arrays?

In [ ]:
# 30. How to find common values between two arrays?
import numpy as np

arr1 = np.random.randint(0,10,10) #low=0, high=10, size=10
print(arr1)
arr2 = np.random.randint(0,10,10)
print(arr2)
print("\n\nCommon values")
print(np.intersect1d(arr1,arr2))

[3 4 4 7 2 5 3 8 1 6]
[9 6 4 5 1 8 2 0 4 2]


Common values
[1 2 4 5 6 8]
